version: "3"
services:
  app:
    tty: true
    container_name: containerize_app_1
    build: ./app 
    command: gunicorn wsgi:app -b 0.0.0.0:8000 --reload
    networks:
      - front-tier
      - back-tier
        
    ports:
      - 8000:8000
    
    volumes:
      - ./app/src:/src/

  nginx:
    container_name: containerize_nginx_1
    build: ./nginx 
    networks:
      - front-tier
      - back-tier
    
    ports:
      - 80:80
      - 443:443
  
    volumes:
      - ./nginx/files/localhost.crt:/etc/nginx/localhost.crt 
      - ./nginx/files/localhost.key:/etc/nginx/localhost.key 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - app

volumes:
  app: {}

networks:
  front-tier:
  back-tier:
