version: "3"
services:

  app:
    container_name: containerize_app_1
    build: ./app 
    
    # Start the app container in development mode listening on port 8000
    # Allow local edits of the app source to be reflected in the running app container without restart (eg: hot code reload)
    command: gunicorn wsgi:app -b 0.0.0.0:8000 --reload
    
    networks:
      - front-tier
      - back-tier
        
    ports:
      - 8000:8000
    
    # Allow local edits of the app source to be reflected in the running app container without restart (eg: hot code reload)
    volumes:
      - ./app/src:/src/


  nginx:
    # Start an nginx container configured with the files from Part One
    container_name: containerize_nginx_1
    build: ./nginx 
    networks:
      - front-tier
      - back-tier
    
    ports:
      - 80:80
      - 443:443
  
    # Ensure the SSL keypair is available to nginx, but is not baked in to the container image
    volumes:
      - ./nginx/files/localhost.crt:/etc/nginx/localhost.crt 
      - ./nginx/files/localhost.key:/etc/nginx/localhost.key 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    # Nginx.conf makes reference to a url that belongs to the app container.
    depends_on:
      - app

volumes:
  app: {}

networks:
  front-tier:
  back-tier:
